services:
  - type: web
    name: mental-health-api
    env: node
    plan: free
    # Based on your package.json scripts
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: DATABASE_URL
        sync: false # You will paste your MongoDB string in the Render Dashboard
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_VERSION
        value: 20.0.0